"""Render docs/CODE-TRACE.md from the published engineering-trace HTML.

The HTML in code-trace-html/ is the source of truth; this script keeps the
Markdown from drifting away from it. Run from the repository root:

    python docs/render-code-trace.py

Requires beautifulsoup4.
"""
import os
import re

from bs4 import BeautifulSoup, NavigableString, Tag

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, "code-trace-html", "arinc615a-gui-engineering.html")
TARGET = os.path.join(HERE, "CODE-TRACE.md")


def inline(node):
    """Flatten an element's children to Markdown-ish inline text."""
    out = []
    for child in node.children:
        if isinstance(child, NavigableString):
            out.append(str(child))
        elif child.name == "code":
            out.append(f"`{child.get_text()}`")
        elif child.name in ("strong", "b"):
            out.append(f"**{inline(child)}**")
        elif child.name in ("em", "i"):
            out.append(f"*{inline(child)}*")
        elif child.name == "a":
            out.append(f"[{inline(child)}]({child.get('href', '')})")
        elif child.name == "br":
            out.append("\n")
        else:
            out.append(inline(child))
    return re.sub(r"[ \t]+", " ", "".join(out)).strip()


def table_md(table):
    rows = []
    columns = 0
    head = table.find("thead")
    if head:
        cells = [inline(th) for th in head.find_all("th")]
        columns = len(cells)
        rows.append("| " + " | ".join(cells) + " |")
        rows.append("| " + " | ".join(["---"] * columns) + " |")
    for tr in table.find("tbody").find_all("tr"):
        cells = [inline(td) for td in tr.find_all(["td", "th"])]
        # a colspan still has to fill its columns or the row will not line up
        span = sum(int(td.get("colspan", 1)) for td in tr.find_all(["td", "th"]))
        if columns and span < columns:
            cells += [""] * (columns - span)
        elif columns and len(cells) < columns:
            cells += [""] * (columns - len(cells))
        rows.append("| " + " | ".join(c.replace("|", r"\|") for c in cells) + " |")
    return "\n".join(rows)


def render(node, out):
    for element in node.children:
        if not isinstance(element, Tag):
            continue
        name = element.name
        if name == "h2":
            out.append(f"### {inline(element)}\n")
        elif name == "h3":
            out.append(f"#### {inline(element)}\n")
        elif name == "h4":
            out.append(f"##### {inline(element)}\n")
        elif name == "p":
            out.append(inline(element) + "\n")
        elif name == "pre":
            out.append("```cpp\n" + element.get_text().strip("\n") + "\n```\n")
        elif name == "ol":
            for index, li in enumerate(element.find_all("li", recursive=False), 1):
                out.append(f"{index}. {inline(li)}")
            out.append("")
        elif name == "ul":
            for li in element.find_all("li", recursive=False):
                out.append(f"- {inline(li)}")
            out.append("")
        elif name == "table":
            out.append(table_md(element) + "\n")
        elif name == "div" and "note" in (element.get("class") or []):
            label = element.find("span", class_="lbl")
            body = [inline(p) for p in element.find_all("p")]
            out.append(f"> **{inline(label) if label else 'Note'}**  ")
            out.append("> " + "  \n> ".join(body) + "\n")
        else:
            render(element, out)


def main():
    soup = BeautifulSoup(open(SOURCE, encoding="utf-8").read(), "html.parser")

    lines = [
        "# Code trace — ARINC 615A graphical data loader",
        "",
        "How a menu action becomes a UDP datagram, and how a protocol callback",
        "arriving on a worker thread becomes a row in a table widget.",
        "",
        "Generated from [code-trace-html/arinc615a-gui-engineering.html]"
        "(code-trace-html/arinc615a-gui-engineering.html), which is the source of",
        "truth. Do not edit this file by hand — regenerate it:",
        "",
        "```bash",
        "python docs/render-code-trace.py",
        "```",
        "",
        "---",
        "",
    ]

    for section in soup.find_all("section"):
        eyebrow_tag = section.find("span", class_="sec-no")
        eyebrow = inline(eyebrow_tag) if eyebrow_tag else ""
        body = []
        render(section, body)
        body = [b for b in body if b.strip() != eyebrow]
        number, _, _ = eyebrow.partition("—")
        for index, block in enumerate(body):
            if block.startswith("### "):
                body[index] = f"## {number.strip()} — {block[4:].strip()}"
                break
        lines.append("\n".join(body).rstrip() + "\n")
        lines.append("---\n")

    text = re.sub(r"\n{3,}", "\n\n", "\n".join(lines))
    with open(TARGET, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text.rstrip() + "\n")
    print(f"wrote {TARGET} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
